apiVersion: v1
kind: Secret
metadata:
  name: techshop-secret
  namespace: techshop
type: Opaque
data:
  POSTGRES_USER: <base64-encoded-username>
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_DB: <base64-encoded-dbname>